# ベースイメージ（PHP 8.2-FPM）
FROM php:8.2-fpm

# 作業ディレクトリを指定
WORKDIR /var/www/html

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
git \
zip \
unzip \
vim \
zsh \
libpq-dev \
netcat-openbsd \
wget \
gnupg2 \
libzip-dev \
ca-certificates \
fonts-liberation \
libnss3 \
libxss1 \
libasound2

# PHP 拡張モジュールのインストール
RUN docker-php-ext-install pdo_pgsql bcmath zip && \
apt-get clean && rm -rf /var/lib/apt/lists/*

# Composer のインストール（マルチステージビルドの場合は Composer イメージからコピー）
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# PHP設定ファイルのコピー
COPY php.ini /usr/local/etc/php/php.ini

# git のグローバル設定（オプション）
RUN git config --global user.name "YourGitHubUserName" \
&& git config --global user.email "your.email@example.com" \
&& git config --global --add safe.directory /var/www/html

# ~/.zshrc を作成し、エイリアスを設定
RUN touch /root/.zshrc \
&& echo "alias ll='ls -alF'" >> /root/.bashrc \
&& echo "alias gs='git status'" >> /root/.bashrc \
&& echo "alias gp='git pull'" >> /root/.bashrc \
&& echo "alias Tt='php artisan knowledge:teach'" >> /root/.bashrc \
&& echo "alias Tr='php artisan chat:run'" >> /root/.bashrc

# zsh をデフォルトシェルに設定
RUN chsh -s $(which zsh)
