FROM nginx:1.18-alpine

ENV TZ=Asia/Tokyo

RUN apk add --no-cache nss-tools curl openssl

# SSL証明書のコピー
COPY ./nginx/ssl/server-cert.pem /etc/nginx/ssl/server-cert.pem
COPY ./nginx/ssl/server-key.pem /etc/nginx/ssl/server-key.pem
RUN chmod 644 /etc/nginx/ssl/server-key.pem

# nginxの設定ファイルのコピー（ここだけ残す）
COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html

CMD ["nginx", "-g", "daemon off;"]
